using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.Text;

namespace FurnitureSolutionAnalyzer;

[Generator]
public class SolutionGenerator : IIncrementalGenerator
{
    void IIncrementalGenerator.Initialize(IncrementalGeneratorInitializationContext context)
    {
        string currentNameSpace = "";
        // 筛选 .xml 后缀的文件, 并转换为 document
        var registerTableProvider = context.AdditionalTextsProvider
            .Where(f => Path.GetExtension(f.Path).Equals(".registerTable", StringComparison.OrdinalIgnoreCase))
            .SelectMany((file, _) =>
            {
                var content = file.GetText().ToString();
                List<SolutionDeclareData> data = [];
                foreach (var lineDummy in content.Split('\n'))
                {
                    var line = lineDummy.Replace(" ", "").Replace("\r", "");
                    if (string.IsNullOrEmpty(line) || line.StartsWith("#")) continue;
                    if (line.StartsWith("//"))
                    {
                        currentNameSpace = line.Substring(2);
                        continue;
                    }
                    var info = line.Split(',');
                    if (info.Length != 4) continue;
                    data.Add(new(
                        info[0],
                        currentNameSpace,
                        info[1],
                        info[2],
                        info[3]));
                }
                return data;
            });

        // 注册源输出
        context.RegisterSourceOutput(registerTableProvider, (spc, data) =>
        {
            var code = GenerateClassSource(data);
            spc.AddSource($"{data.SolutionName}Solution.g.cs", SourceText.From(code, Encoding.UTF8));
        });


        context.RegisterSourceOutput(registerTableProvider.Collect(), (spc, data) =>
        {
            var code = GenerateYukaSolutionRegister(data);
            spc.AddSource($"FurnitureSolution.g.cs", SourceText.From(code, Encoding.UTF8));
        });
    }
    private static string GenerateClassSource(SolutionDeclareData data)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine();

        sb.AppendLine("using FurnitureSolution.Solutions.Core;");
        sb.AppendLine("using Terraria.ID;");
        sb.AppendLine("using Microsoft.Xna.Framework;");

        sb.AppendLine($"namespace FurnitureSolution.Solutions.{data.CategoryNameSpace};");


        sb.AppendLine($"public class {data.SolutionName}Solution : SolutionItemBase<{data.SolutionName}SolutionProjectile>");
        sb.AppendLine("{");
        sb.AppendLine($"    public override string Texture => \"FurnitureSolution/Solutions/SolutionItemIcon/Solution{data.RowIndex}\";");
        sb.AppendLine("    public override void AddRecipes()");
        sb.AppendLine("    {");
        sb.AppendLine("        CreateRecipe()");
        sb.AppendLine("            .AddIngredient(ItemID.GreenSolution)");
        sb.AppendLine($"            .AddIngredient({data.IngredientType}, 5)");
        sb.AppendLine("            .Register();");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        sb.AppendLine($"public class {data.SolutionName}SolutionProjectile : SolutionProjectileBase");
        sb.AppendLine("{");
        sb.AppendLine($"    public {data.SolutionName}SolutionProjectile() : base(furnitureTableRowIndex: {data.RowIndex})");
        sb.AppendLine("    {");
        sb.AppendLine($"        FurnitureSolution.FurnitureSetIndexDictionary[\"{data.SolutionName}\"] = {data.RowIndex};");
        sb.AppendLine("    }");
        sb.AppendLine("    public override void ModifyNewDust(");
        sb.AppendLine("        ref int dustType,");
        sb.AppendLine("        ref Vector2 position,");
        sb.AppendLine("        ref Vector2 velocity,");
        sb.AppendLine("        ref int extraWidth,");
        sb.AppendLine("        ref float extraScale,");
        sb.AppendLine("        ref int alpha,");
        sb.AppendLine("        ref Color color)");
        sb.AppendLine("    {");
        sb.AppendLine($"        dustType = {data.DustType};");
        sb.AppendLine("    }");
        sb.AppendLine("}");



        return sb.ToString();
    }
    private static string GenerateYukaSolutionRegister(ImmutableArray<SolutionDeclareData> data)
    {
        HashSet<string> Categories = [];
        foreach (var set in data)
            Categories.Add(set.CategoryNameSpace);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine();

        foreach (var category in Categories)
            sb.AppendLine($"using FurnitureSolution.Solutions.{category};");
        sb.AppendLine("using Terraria.ID;");
        sb.AppendLine("using Terraria.ModLoader;");

        sb.AppendLine($"namespace FurnitureSolution;");

        sb.AppendLine("partial class FurnitureSolution");
        sb.AppendLine("{");
        sb.AppendLine("    private void RegisterYukaSolution(Mod mod)");
        sb.AppendLine("    {");
        foreach (var set in data) 
        {
            sb.AppendLine("        mod.Call(");
            sb.AppendLine("            \"YukaSolutionInfo\",");
            sb.AppendLine("            this,");
            sb.AppendLine($"            ModContent.ItemType<{set.SolutionName}Solution>(),");
            sb.AppendLine($"            ModContent.ProjectileType<{set.SolutionName}SolutionProjectile>(),");
            sb.AppendLine($"            (int){set.DustType});");
            sb.AppendLine();
        }

        sb.AppendLine("    }");

        sb.AppendLine("}");
        return sb.ToString();
    }
}
